const ROUTE_PATH = {
  HOME_VIEW: '/',
  ABOUT: '/about',
  LOGIN_PAGE: '/login-page',
  REGISTER_PAGE: '/register',
  EMPLOYEE_MANAGEMENT: '/employee-management',
  EMPLOYEE_REGISTER: '/evployee-register',
  ACCOUNT_SETTING: '/account-setting',
  FARM_MANAGEMENT: '/farm-management',
  BIRD_MANAGEMENT: '/bird-management',
  BIRD_INFORMATION: '/bird-information',
  SELECT_MANAGE: '/select-manage',
  BIRD_REGISTER: '/bird-register',
  NETWORK_ERROR: '/network-error',
  BIRD_ACTIVITYLIST: '/bird-planning-list',
  BIRD_CREATEACTIVIT: '/bird-planning-create',
  BIRD_BREEDING: '/bird-breeding',
  BIRD_BREEDINGDETAILS: '/bird-breeding-details',
  BIRD_BREEDINGCREATE: '/bird-breeding-create',
  BIRD_PEDIGREE: '/bird-pedigree',
  BIRD_ACTIVITYDETAIL: '/bird-planning-detail',
  BIRD_SPECIES_LIST: '/bird-species-list',
  BIRD_SPECIES_CREATE: '/bird-species-create',
  BIRD_SPECIES_DETAIL: '/bird-species-details',
  EGG_EDIT: '/egg-edit',
  FARM_STAT: '/farm-statistics',
  COMPONENT_TEST: '/component-test'
}

export default ROUTE_PATH
